#!/bin/sh

# Copyright (C) Guangzhou FriendlyARM Computer Tech. Co., Ltd.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.

if [ -z "$1" ] || [ -z "$2" ]; then
	echo "Usage: $0 IFACE <WPA-ctrl-event>"
	exit 1
fi

case "$2" in
CONNECTED)
	udhcpc -p /var/run/dhcp_$1 -i $1
	;;
DISCONNECTED)
	[ -e /var/run/dhcp_$1 ] && kill `cat /var/run/dhcp_$1`
	;;
esac

exit 0
